import { useState } from 'react';
import { ME } from '../constants';
import { cntDone } from '../constants';

export default function WeeklyReport({ state, fullState, onClose }) {
  const [copied, setCopied] = useState(false);

  const subjects = state.subjects || [];
  const totalStudyMins = state.studyMins || 0;
  const assignments = state.assignments || [];
  const submitted = assignments.filter(a => a.status === 'submitted').length;
  const tasksDone = cntDone(state);
  const streak = state.streak || 0;

  const weekData = state.weekData || [];
  const recentMoods = weekData.slice(-7).map(d => d.mood).filter(Boolean);
  const moodEmojis = recentMoods.map(m => ME[m] || '·').join(' ');

  // Top subjects by time
  const topSubjects = [...subjects].sort((a, b) => b.done - a.done).slice(0, 5);

  const report = `📚 *${state.name}'s Weekly Study Report*
━━━━━━━━━━━━━━━━━━

⏱ *Study Time:* ${(totalStudyMins / 60).toFixed(1)} hours
✅ *Tasks Done:* ${tasksDone}
📋 *Assignments Submitted:* ${submitted}
🔥 *Current Streak:* ${streak} days

📖 *Top Subjects:*
${topSubjects.map(s => `  • ${s.name}: ${Math.floor(s.done / 60)}h ${s.done % 60}m`).join('\n')}

😊 *Mood This Week:* ${moodEmojis || '(no data)'}

━━━━━━━━━━━━━━━━━━
Generated by Our Study Planner 💖`;

  const copyToClipboard = () => {
    navigator.clipboard.writeText(report).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    });
  };

  return (
    <div className="alovo open" onClick={onClose}>
      <div className="albx" onClick={e => e.stopPropagation()} style={{ maxHeight: '85vh', overflowY: 'auto' }}>
        <div className="nmh" />
        <button className="nmclose" onClick={onClose}>✕</button>

        <div style={{ marginBottom: '20px' }}>
          <div style={{ fontSize: '11px', fontWeight: 700, color: 'var(--primary)', textTransform: 'uppercase', letterSpacing: '1px', marginBottom: '4px' }}>Weekly Summary</div>
          <h2 style={{ margin: 0, fontStyle: 'italic' }}>{state.name}'s Report 📊</h2>
        </div>

        {/* Stats grid */}
        <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '10px', marginBottom: '20px' }}>
          {[
            { label: 'Study Time', value: `${(totalStudyMins / 60).toFixed(1)}h`, icon: '⏱️', color: 'var(--primary)' },
            { label: 'Tasks Done', value: tasksDone, icon: '✅', color: '#27ae60' },
            { label: 'Day Streak', value: `${streak}🔥`, icon: '🔥', color: '#e28743' },
            { label: 'Assignments', value: `${submitted} done`, icon: '📋', color: '#5da9e9' },
          ].map(item => (
            <div key={item.label} style={{ background: 'var(--surface-container-low)', borderRadius: '14px', padding: '14px', textAlign: 'center' }}>
              <div style={{ fontSize: '22px', marginBottom: '4px' }}>{item.icon}</div>
              <div style={{ fontWeight: 800, fontSize: '18px', color: item.color }}>{item.value}</div>
              <div style={{ fontSize: '10px', color: 'var(--text-dim)', fontWeight: 600 }}>{item.label}</div>
            </div>
          ))}
        </div>

        {/* Top subjects */}
        {topSubjects.length > 0 && (
          <>
            <div style={{ fontWeight: 700, fontSize: '13px', marginBottom: '10px' }}>📖 Top Subjects</div>
            {topSubjects.map((s, i) => {
              const maxMins = topSubjects[0].done || 1;
              return (
                <div key={s.id} style={{ marginBottom: '8px' }}>
                  <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '4px', fontSize: '12px' }}>
                    <span style={{ fontWeight: 700 }}>{s.name}</span>
                    <span style={{ color: 'var(--text-dim)' }}>{Math.floor(s.done / 60)}h {s.done % 60}m</span>
                  </div>
                  <div style={{ height: '6px', background: 'var(--surface-container-low)', borderRadius: '6px', overflow: 'hidden' }}>
                    <div style={{ width: `${(s.done / maxMins) * 100}%`, height: '100%', background: 'var(--primary)', borderRadius: '6px' }} />
                  </div>
                </div>
              );
            })}
          </>
        )}

        {/* Mood trail */}
        {moodEmojis && (
          <div style={{ background: 'var(--surface-container-low)', borderRadius: '14px', padding: '14px', margin: '16px 0', textAlign: 'center' }}>
            <div style={{ fontSize: '11px', color: 'var(--text-dim)', marginBottom: '6px', fontWeight: 600 }}>Mood This Week</div>
            <div style={{ fontSize: '22px', letterSpacing: '6px' }}>{moodEmojis}</div>
          </div>
        )}

        {/* Report text preview */}
        <div style={{ background: 'var(--surface-container-low)', borderRadius: '14px', padding: '14px', marginBottom: '16px' }}>
          <div style={{ fontSize: '11px', color: 'var(--text-dim)', marginBottom: '8px', fontWeight: 700 }}>📋 Share Preview</div>
          <pre style={{ fontSize: '11px', fontFamily: 'monospace', whiteSpace: 'pre-wrap', color: 'var(--text)', margin: 0, lineHeight: 1.6 }}>{report}</pre>
        </div>

        {/* Actions */}
        <div style={{ display: 'flex', gap: '10px' }}>
          <button
            onClick={copyToClipboard}
            style={{
              flex: 1, background: copied ? '#27ae60' : 'var(--primary)',
              color: '#fff', border: 'none', borderRadius: '16px',
              padding: '14px', fontSize: '14px', fontWeight: 800, cursor: 'pointer',
              transition: 'background 0.2s'
            }}
          >
            {copied ? '✅ Copied!' : '📤 Copy to Share'}
          </button>
          <button
            onClick={() => window.print()}
            style={{ background: 'var(--surface-container-low)', border: 'none', borderRadius: '16px', padding: '14px', fontSize: '14px', cursor: 'pointer' }}
          >
            🖨️
          </button>
        </div>
      </div>
    </div>
  );
}
